
// File auto-generated by Padrick 0.3.6
module cheshire_padframe_sim_main_pads
  import pkg_cheshire_padframe_sim::*;
  import pkg_internal_cheshire_padframe_sim_main::*;
(
  output pad_domain_main_static_connection_signals_pad2soc_t static_connection_signals_pad2soc,
  input  pad_domain_main_static_connection_signals_soc2pad_t static_connection_signals_soc2pad,
 // Dynamic Pad control signals, these signals are controlled by the multiplexer in the correpsongin pad_controller module
  // Landing Pads
  inout wire logic pad_core_clk_pad,
  inout wire logic pad_ref_clk_pad,
  inout wire logic pad_reset_n_pad,
  inout wire logic pad_testmode_pad,
  inout wire logic pad_bootmode0_pad,
  inout wire logic pad_bootmode1_pad,
  inout wire logic pad_jtag_tck_pad,
  inout wire logic pad_jtag_trst_n_pad,
  inout wire logic pad_jtag_tms_pad,
  inout wire logic pad_jtag_tdi_pad,
  inout wire logic pad_jtag_tdo_pad,
  inout wire logic pad_uart_rx_pad,
  inout wire logic pad_uart_tx_pad,
  inout wire logic pad_spim_sck_pad,
  inout wire logic pad_spim_csb0_pad,
  inout wire logic pad_spim_csb1_pad,
  inout wire logic pad_spim_sd0_pad,
  inout wire logic pad_spim_sd1_pad,
  inout wire logic pad_spim_sd2_pad,
  inout wire logic pad_spim_sd3_pad,
  inout wire logic pad_i2c_scl_pad,
  inout wire logic pad_i2c_sda_pad,
  inout wire logic pad_ddr_link_clk_in_pad,
  inout wire logic pad_ddr_link_clk_out_pad,
  inout wire logic pad_ddr_link_in0_pad,
  inout wire logic pad_ddr_link_in1_pad,
  inout wire logic pad_ddr_link_in2_pad,
  inout wire logic pad_ddr_link_in3_pad,
  inout wire logic pad_ddr_link_out0_pad,
  inout wire logic pad_ddr_link_out1_pad,
  inout wire logic pad_ddr_link_out2_pad,
  inout wire logic pad_ddr_link_out3_pad,
  inout wire logic pad_vga_hsync_pad,
  inout wire logic pad_vga_vsync_pad,
  inout wire logic pad_vga_red_0_pad,
  inout wire logic pad_vga_red_1_pad,
  inout wire logic pad_vga_red_2_pad,
  inout wire logic pad_vga_green_0_pad,
  inout wire logic pad_vga_green_1_pad,
  inout wire logic pad_vga_green_2_pad,
  inout wire logic pad_vga_blue_0_pad,
  inout wire logic pad_vga_blue_1_pad,
  inout wire logic pad_rpc_clk_pad,
  inout wire logic pad_rpc_clk_n_pad,
  inout wire logic pad_rpc_cs_n_pad,
  inout wire logic pad_rpc_stb_pad,
  inout wire logic pad_rpc_dqs_pad,
  inout wire logic pad_rpc_dqs_n_pad,
  inout wire logic pad_rpc_db0_pad,
  inout wire logic pad_rpc_db1_pad,
  inout wire logic pad_rpc_db2_pad,
  inout wire logic pad_rpc_db3_pad,
  inout wire logic pad_rpc_db4_pad,
  inout wire logic pad_rpc_db5_pad,
  inout wire logic pad_rpc_db6_pad,
  inout wire logic pad_rpc_db7_pad,
  inout wire logic pad_rpc_db8_pad,
  inout wire logic pad_rpc_db9_pad,
  inout wire logic pad_rpc_db10_pad,
  inout wire logic pad_rpc_db11_pad,
  inout wire logic pad_rpc_db12_pad,
  inout wire logic pad_rpc_db13_pad,
  inout wire logic pad_rpc_db14_pad,
  inout wire logic pad_rpc_db15_pad
  );

   // Pad instantiations
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_core_clk (
    .pad_io(pad_core_clk_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b1)),
    .c_o(static_connection_signals_pad2soc.core_clk_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(1'b0)),
    .oen_i(1'(1'b1))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_ref_clk (
    .pad_io(pad_ref_clk_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b1)),
    .c_o(static_connection_signals_pad2soc.ref_clk_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(1'b0)),
    .oen_i(1'(1'b1))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_reset_n (
    .pad_io(pad_reset_n_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b1)),
    .c_o(static_connection_signals_pad2soc.reset_n_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(1'b0)),
    .oen_i(1'(1'b1))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_testmode (
    .pad_io(pad_testmode_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b1)),
    .c_o(static_connection_signals_pad2soc.testmode_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(1'b0)),
    .oen_i(1'(1'b1))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_bootmode0 (
    .pad_io(pad_bootmode0_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b1)),
    .c_o(static_connection_signals_pad2soc.bootmode0_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(1'b0)),
    .oen_i(1'(1'b1))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_bootmode1 (
    .pad_io(pad_bootmode1_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b1)),
    .c_o(static_connection_signals_pad2soc.bootmode1_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(1'b0)),
    .oen_i(1'(1'b1))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_jtag_tck (
    .pad_io(pad_jtag_tck_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b1)),
    .c_o(static_connection_signals_pad2soc.jtag_tck_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(1'b0)),
    .oen_i(1'(1'b1))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_jtag_trst_n (
    .pad_io(pad_jtag_trst_n_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b1)),
    .c_o(static_connection_signals_pad2soc.jtag_trst_n_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(1'b0)),
    .oen_i(1'(1'b1))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_jtag_tms (
    .pad_io(pad_jtag_tms_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b1)),
    .c_o(static_connection_signals_pad2soc.jtag_tms_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(1'b0)),
    .oen_i(1'(1'b1))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_jtag_tdi (
    .pad_io(pad_jtag_tdi_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b1)),
    .c_o(static_connection_signals_pad2soc.jtag_tdi_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(1'b0)),
    .oen_i(1'(1'b1))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_jtag_tdo (
    .pad_io(pad_jtag_tdo_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b0)),
    .i_i(1'(static_connection_signals_soc2pad.jtag_tdo_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_uart_rx (
    .pad_io(pad_uart_rx_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b1)),
    .c_o(static_connection_signals_pad2soc.uart_rx_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(1'b0)),
    .oen_i(1'(1'b1))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_uart_tx (
    .pad_io(pad_uart_tx_pad),
    .pe_i(1'(1'b1)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b0)),
    .i_i(1'(static_connection_signals_soc2pad.uart_tx_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_spim_sck (
    .pad_io(pad_spim_sck_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b0)),
    .i_i(1'(static_connection_signals_soc2pad.spim_sck_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.spim_sck_en_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_spim_csb0 (
    .pad_io(pad_spim_csb0_pad),
    .pe_i(1'(1'b1)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b0)),
    .i_i(1'(static_connection_signals_soc2pad.spim_csb0_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.spim_csb_en0_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_spim_csb1 (
    .pad_io(pad_spim_csb1_pad),
    .pe_i(1'(1'b1)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b0)),
    .i_i(1'(static_connection_signals_soc2pad.spim_csb1_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.spim_csb_en1_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_spim_sd0 (
    .pad_io(pad_spim_sd0_pad),
    .pe_i(1'(1'b1)),
    .ie_i(1'(~static_connection_signals_soc2pad.spim_sd_en0_c2p)),
    .c_o(static_connection_signals_pad2soc.spim_sd0_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(static_connection_signals_soc2pad.spim_sd0_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.spim_sd_en0_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_spim_sd1 (
    .pad_io(pad_spim_sd1_pad),
    .pe_i(1'(1'b1)),
    .ie_i(1'(~static_connection_signals_soc2pad.spim_sd_en1_c2p)),
    .c_o(static_connection_signals_pad2soc.spim_sd1_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(static_connection_signals_soc2pad.spim_sd1_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.spim_sd_en1_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_spim_sd2 (
    .pad_io(pad_spim_sd2_pad),
    .pe_i(1'(1'b1)),
    .ie_i(1'(~static_connection_signals_soc2pad.spim_sd_en2_c2p)),
    .c_o(static_connection_signals_pad2soc.spim_sd2_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(static_connection_signals_soc2pad.spim_sd2_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.spim_sd_en2_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_spim_sd3 (
    .pad_io(pad_spim_sd3_pad),
    .pe_i(1'(1'b1)),
    .ie_i(1'(~static_connection_signals_soc2pad.spim_sd_en3_c2p)),
    .c_o(static_connection_signals_pad2soc.spim_sd3_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(static_connection_signals_soc2pad.spim_sd3_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.spim_sd_en3_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_i2c_scl (
    .pad_io(pad_i2c_scl_pad),
    .pe_i(1'(1'b1)),
    .ie_i(1'(~static_connection_signals_soc2pad.i2c_scl_en_c2p)),
    .c_o(static_connection_signals_pad2soc.i2c_scl_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(static_connection_signals_soc2pad.i2c_scl_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.i2c_scl_en_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_i2c_sda (
    .pad_io(pad_i2c_sda_pad),
    .pe_i(1'(1'b1)),
    .ie_i(1'(~static_connection_signals_soc2pad.i2c_sda_en_c2p)),
    .c_o(static_connection_signals_pad2soc.i2c_sda_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(static_connection_signals_soc2pad.i2c_sda_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.i2c_sda_en_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_ddr_link_clk_in (
    .pad_io(pad_ddr_link_clk_in_pad),
    .pe_i(1'(1'b1)),
    .ie_i(1'(1'b1)),
    .c_o(static_connection_signals_pad2soc.ddr_link_clk_in_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(1'b0)),
    .oen_i(1'(1'b1))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_ddr_link_clk_out (
    .pad_io(pad_ddr_link_clk_out_pad),
    .pe_i(1'(1'b1)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.ddr_link_clk_out_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_ddr_link_in0 (
    .pad_io(pad_ddr_link_in0_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b1)),
    .c_o(static_connection_signals_pad2soc.ddr_link_in0_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(1'b0)),
    .oen_i(1'(1'b1))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_ddr_link_in1 (
    .pad_io(pad_ddr_link_in1_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b1)),
    .c_o(static_connection_signals_pad2soc.ddr_link_in1_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(1'b0)),
    .oen_i(1'(1'b1))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_ddr_link_in2 (
    .pad_io(pad_ddr_link_in2_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b1)),
    .c_o(static_connection_signals_pad2soc.ddr_link_in2_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(1'b0)),
    .oen_i(1'(1'b1))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_ddr_link_in3 (
    .pad_io(pad_ddr_link_in3_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b1)),
    .c_o(static_connection_signals_pad2soc.ddr_link_in3_p2c),
    .ds_i(1'(1'b0)),
    .i_i(1'(1'b0)),
    .oen_i(1'(1'b1))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_ddr_link_out0 (
    .pad_io(pad_ddr_link_out0_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.ddr_link_out0_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_ddr_link_out1 (
    .pad_io(pad_ddr_link_out1_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.ddr_link_out1_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_ddr_link_out2 (
    .pad_io(pad_ddr_link_out2_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.ddr_link_out2_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_ddr_link_out3 (
    .pad_io(pad_ddr_link_out3_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.ddr_link_out3_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_vga_hsync (
    .pad_io(pad_vga_hsync_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.vga_hsync_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_vga_vsync (
    .pad_io(pad_vga_vsync_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.vga_vsync_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_vga_red_0 (
    .pad_io(pad_vga_red_0_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.vga_red0_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_vga_red_1 (
    .pad_io(pad_vga_red_1_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.vga_red1_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_vga_red_2 (
    .pad_io(pad_vga_red_2_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.vga_red2_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_vga_green_0 (
    .pad_io(pad_vga_green_0_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.vga_green0_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_vga_green_1 (
    .pad_io(pad_vga_green_1_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.vga_green1_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_vga_green_2 (
    .pad_io(pad_vga_green_2_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.vga_green2_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_vga_blue_0 (
    .pad_io(pad_vga_blue_0_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.vga_blue0_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_vga_blue_1 (
    .pad_io(pad_vga_blue_1_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.vga_blue1_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_clk (
    .pad_io(pad_rpc_clk_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_clk_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_clk_n (
    .pad_io(pad_rpc_clk_n_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_clk_n_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_cs_n (
    .pad_io(pad_rpc_cs_n_pad),
    .pe_i(1'(1'b1)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_cs_n_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_stb (
    .pad_io(pad_rpc_stb_pad),
    .pe_i(1'(1'b0)),
    .ie_i(1'(1'b0)),
    .c_o(),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_stb_c2p)),
    .oen_i(1'(1'b0))
  );
   func_pad #(
    .PullUpOrDown(1'b0)
    ) i_rpc_dqs (
    .pad_io(pad_rpc_dqs_pad),
    .pe_i(1'(1'b1)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_dqs_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_dqs_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_dqs_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_dqs_oe_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_dqs_n (
    .pad_io(pad_rpc_dqs_n_pad),
    .pe_i(1'(static_connection_signals_soc2pad.rpc_dqs_pe_c2p)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_dqs_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_dqs_n_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_dqs_n_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_dqs_oe_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_db0 (
    .pad_io(pad_rpc_db0_pad),
    .pe_i(1'(static_connection_signals_soc2pad.rpc_db_pe_c2p)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_db_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_db0_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_db0_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_db_oe_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_db1 (
    .pad_io(pad_rpc_db1_pad),
    .pe_i(1'(static_connection_signals_soc2pad.rpc_db_pe_c2p)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_db_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_db1_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_db1_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_db_oe_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_db2 (
    .pad_io(pad_rpc_db2_pad),
    .pe_i(1'(static_connection_signals_soc2pad.rpc_db_pe_c2p)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_db_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_db2_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_db2_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_db_oe_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_db3 (
    .pad_io(pad_rpc_db3_pad),
    .pe_i(1'(static_connection_signals_soc2pad.rpc_db_pe_c2p)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_db_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_db3_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_db3_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_db_oe_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_db4 (
    .pad_io(pad_rpc_db4_pad),
    .pe_i(1'(static_connection_signals_soc2pad.rpc_db_pe_c2p)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_db_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_db4_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_db4_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_db_oe_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_db5 (
    .pad_io(pad_rpc_db5_pad),
    .pe_i(1'(static_connection_signals_soc2pad.rpc_db_pe_c2p)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_db_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_db5_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_db5_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_db_oe_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_db6 (
    .pad_io(pad_rpc_db6_pad),
    .pe_i(1'(static_connection_signals_soc2pad.rpc_db_pe_c2p)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_db_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_db6_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_db6_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_db_oe_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_db7 (
    .pad_io(pad_rpc_db7_pad),
    .pe_i(1'(static_connection_signals_soc2pad.rpc_db_pe_c2p)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_db_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_db7_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_db7_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_db_oe_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_db8 (
    .pad_io(pad_rpc_db8_pad),
    .pe_i(1'(static_connection_signals_soc2pad.rpc_db_pe_c2p)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_db_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_db8_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_db8_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_db_oe_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_db9 (
    .pad_io(pad_rpc_db9_pad),
    .pe_i(1'(static_connection_signals_soc2pad.rpc_db_pe_c2p)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_db_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_db9_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_db9_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_db_oe_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_db10 (
    .pad_io(pad_rpc_db10_pad),
    .pe_i(1'(static_connection_signals_soc2pad.rpc_db_pe_c2p)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_db_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_db10_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_db10_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_db_oe_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_db11 (
    .pad_io(pad_rpc_db11_pad),
    .pe_i(1'(static_connection_signals_soc2pad.rpc_db_pe_c2p)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_db_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_db11_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_db11_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_db_oe_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_db12 (
    .pad_io(pad_rpc_db12_pad),
    .pe_i(1'(static_connection_signals_soc2pad.rpc_db_pe_c2p)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_db_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_db12_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_db12_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_db_oe_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_db13 (
    .pad_io(pad_rpc_db13_pad),
    .pe_i(1'(static_connection_signals_soc2pad.rpc_db_pe_c2p)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_db_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_db13_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_db13_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_db_oe_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_db14 (
    .pad_io(pad_rpc_db14_pad),
    .pe_i(1'(static_connection_signals_soc2pad.rpc_db_pe_c2p)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_db_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_db14_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_db14_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_db_oe_c2p))
  );
   func_pad #(
    .PullUpOrDown(1'b1)
    ) i_rpc_db15 (
    .pad_io(pad_rpc_db15_pad),
    .pe_i(1'(static_connection_signals_soc2pad.rpc_db_pe_c2p)),
    .ie_i(1'(static_connection_signals_soc2pad.rpc_db_ie_c2p)),
    .c_o(static_connection_signals_pad2soc.rpc_db15_p2c),
    .ds_i(1'(1'b1)),
    .i_i(1'(static_connection_signals_soc2pad.rpc_db15_c2p)),
    .oen_i(1'(~static_connection_signals_soc2pad.rpc_db_oe_c2p))
  );

endmodule : cheshire_padframe_sim_main_pads
