// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package cheshire_padframe_sim_main_config_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 2;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } hw_version;
    struct packed {
      logic [15:0] q;
    } padcount;
  } cheshire_padframe_sim_main_config_reg2hw_info_reg_t;

  // Register -> HW type
  typedef struct packed {
    cheshire_padframe_sim_main_config_reg2hw_info_reg_t info; // [31:0]
  } cheshire_padframe_sim_main_config_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] CHESHIRE_PADFRAME_SIM_MAIN_CONFIG_INFO_OFFSET = 2'h 0;

  // Register index
  typedef enum int {
    CHESHIRE_PADFRAME_SIM_MAIN_CONFIG_INFO
  } cheshire_padframe_sim_main_config_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] CHESHIRE_PADFRAME_SIM_MAIN_CONFIG_PERMIT [1] = '{
    4'b 1111  // index[0] CHESHIRE_PADFRAME_SIM_MAIN_CONFIG_INFO
  };

endpackage

