
// File auto-generated by Padrick 0.3.6
package pkg_internal_cheshire_padframe_sim_main;


  // Indices definitions

  // Dynamic Pad  instance index
endpackage : pkg_internal_cheshire_padframe_sim_main
