
// File auto-generated by Padrick 0.3.6
package pkg_cheshire_padframe_sim;

  //Structs for main

  //Static connections signals
   typedef struct packed {
      logic        ddr_link_clk_out_c2p;
      logic        ddr_link_out0_c2p;
      logic        ddr_link_out1_c2p;
      logic        ddr_link_out2_c2p;
      logic        ddr_link_out3_c2p;
      logic        i2c_scl_c2p;
      logic        i2c_scl_en_c2p;
      logic        i2c_sda_c2p;
      logic        i2c_sda_en_c2p;
      logic        jtag_tdo_c2p;
      logic        rpc_clk_c2p;
      logic        rpc_clk_n_c2p;
      logic        rpc_cs_n_c2p;
      logic        rpc_db0_c2p;
      logic        rpc_db1_c2p;
      logic        rpc_db2_c2p;
      logic        rpc_db3_c2p;
      logic        rpc_db4_c2p;
      logic        rpc_db5_c2p;
      logic        rpc_db6_c2p;
      logic        rpc_db7_c2p;
      logic        rpc_db8_c2p;
      logic        rpc_db9_c2p;
      logic        rpc_db10_c2p;
      logic        rpc_db11_c2p;
      logic        rpc_db12_c2p;
      logic        rpc_db13_c2p;
      logic        rpc_db14_c2p;
      logic        rpc_db15_c2p;
      logic        rpc_db_ie_c2p;
      logic        rpc_db_oe_c2p;
      logic        rpc_db_pe_c2p;
      logic        rpc_dqs_c2p;
      logic        rpc_dqs_ie_c2p;
      logic        rpc_dqs_n_c2p;
      logic        rpc_dqs_oe_c2p;
      logic        rpc_dqs_pe_c2p;
      logic        rpc_stb_c2p;
      logic        spim_csb0_c2p;
      logic        spim_csb1_c2p;
      logic        spim_csb_en0_c2p;
      logic        spim_csb_en1_c2p;
      logic        spim_sck_c2p;
      logic        spim_sck_en_c2p;
      logic        spim_sd0_c2p;
      logic        spim_sd1_c2p;
      logic        spim_sd2_c2p;
      logic        spim_sd3_c2p;
      logic        spim_sd_en0_c2p;
      logic        spim_sd_en1_c2p;
      logic        spim_sd_en2_c2p;
      logic        spim_sd_en3_c2p;
      logic        uart_tx_c2p;
      logic        vga_blue0_c2p;
      logic        vga_blue1_c2p;
      logic        vga_green0_c2p;
      logic        vga_green1_c2p;
      logic        vga_green2_c2p;
      logic        vga_hsync_c2p;
      logic        vga_red0_c2p;
      logic        vga_red1_c2p;
      logic        vga_red2_c2p;
      logic        vga_vsync_c2p;
     } pad_domain_main_static_connection_signals_soc2pad_t;

   typedef struct packed {
      logic        bootmode0_p2c;
      logic        bootmode1_p2c;
      logic        core_clk_p2c;
      logic        ddr_link_clk_in_p2c;
      logic        ddr_link_in0_p2c;
      logic        ddr_link_in1_p2c;
      logic        ddr_link_in2_p2c;
      logic        ddr_link_in3_p2c;
      logic        i2c_scl_p2c;
      logic        i2c_sda_p2c;
      logic        jtag_tck_p2c;
      logic        jtag_tdi_p2c;
      logic        jtag_tms_p2c;
      logic        jtag_trst_n_p2c;
      logic        ref_clk_p2c;
      logic        reset_n_p2c;
      logic        rpc_db0_p2c;
      logic        rpc_db1_p2c;
      logic        rpc_db2_p2c;
      logic        rpc_db3_p2c;
      logic        rpc_db4_p2c;
      logic        rpc_db5_p2c;
      logic        rpc_db6_p2c;
      logic        rpc_db7_p2c;
      logic        rpc_db8_p2c;
      logic        rpc_db9_p2c;
      logic        rpc_db10_p2c;
      logic        rpc_db11_p2c;
      logic        rpc_db12_p2c;
      logic        rpc_db13_p2c;
      logic        rpc_db14_p2c;
      logic        rpc_db15_p2c;
      logic        rpc_dqs_n_p2c;
      logic        rpc_dqs_p2c;
      logic        spim_sd0_p2c;
      logic        spim_sd1_p2c;
      logic        spim_sd2_p2c;
      logic        spim_sd3_p2c;
      logic        testmode_p2c;
      logic        uart_rx_p2c;
     } pad_domain_main_static_connection_signals_pad2soc_t;


  //Toplevel structs

  typedef struct packed {
    pad_domain_main_static_connection_signals_pad2soc_t main;
  } static_connection_signals_pad2soc_t;

  typedef struct packed {
    pad_domain_main_static_connection_signals_soc2pad_t main;
  } static_connection_signals_soc2pad_t;



endpackage : pkg_cheshire_padframe_sim
